spring:
  datasource:
    url: jdbc:mysql://my-rds.cuxgidnqcd32.ap-northeast-2.rds.amazonaws.com:3306/my_rds?useUnicode=true&serverTimezone=Asia/Seoul
    username: myo220211
    password: 
  thymeleaf:
#    prefix: classpath:/html/ default?? ????? ??? ??? ????
#    suffix: .fm
